imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - "::OhGoogleMaps/google_maps_form_widget.html.twig"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    filters:
        cssrewrite: ~

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Doctrine Migrations
doctrine_migrations:
    dir_name:   "%kernel.root_dir%/../src/FinquesFarnos/AppBundle/DoctrineMigrations"
    namespace:  AppBundle\Migrations

# Stof Doctrine Extensions
stof_doctrine_extensions:
    default_locale:         "%locale%"
    translation_fallback:   true
    orm:
        default:
            translatable:   true
            softdeleteable: false
            timestampable:  true
            sluggable:      true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Sonata Admin
sonata_admin:
    title:      "Finques Farnós"
    title_logo: "bundles/app/images/logo-ff-mini.jpg"
    options:
        html5_validate: true
        confirm_exit:   true
        use_select2:    true
        pager_links:    5
    persist_filters: true
    templates:
        layout: ::Admin/custom_layout.html.twig
    dashboard:
        blocks:
            -
                position: left
                type: sonata.admin.block.admin_list
            -
                position: right
                type: sonata.block.service.text
                settings:
                    content: >
                        <h1 style="margin: 0 0 10px 0">Administrador de continguts</h1>
                        <h4 style="margin: 0 0 40px 0">Benvingut a l'administrador de continguts de la pàgina web <a href="http://www.finquesfarnos.com" target="_blank">www.finquesfarnos.com</a></h4>
                        <p>Escull una opció del menú per continuar. Per rebre assitència tècnica o ajuda envieu un missatge a <a href="mailto:suport@flux.cat">suport@flux.cat</a></p>

# Sonata Block
sonata_block:
    default_contexts: [admin]
    blocks:
        sonata.admin.block.admin_list:
        sonata.block.service.text:
        sonata.user.block.menu:    # used to display the menu in profile pages
        sonata.user.block.account: # used to display menu option (login option)

# Sonata User
sonata_user:
    security_acl: false
    manager_type: orm

# FOS User
fos_user:
    db_driver:      orm
    firewall_name:  main
    user_class:     Application\Sonata\UserBundle\Entity\User
    group:
        group_class:   Application\Sonata\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager
    service:
        user_manager: sonata.user.orm.user_manager

# Vich Uploader
vich_uploader:
    db_driver: orm
    mappings:
        property_image:
            namer:              vich_uploader.namer_uniqid
            uri_prefix:         /uploads/images
            upload_destination: %kernel.root_dir%/../web/uploads/images

# Liip Imagine
liip_imagine:
    resolvers:
       default:
          web_path: ~
    filter_sets:
        cache: ~
        60x60:
            quality: 90
            filters:
                thumbnail: { size: [60, 60], mode: outbound }
        300xY:
            quality: 75
            filters:
                thumbnail: { size: [300, null], mode: outbound }

# A2lix Translations
a2lix_translation_form:
    locales:          [ es, en ]
    default_required: true
    manager_registry: doctrine
    templating:       "::A2lix/default.html.twig"
