imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: sonata.yml }
    - { resource: media.yml }

# Framework
framework:
    translator:      { fallback: "%locale%" }
    validation:      { enable_annotations: true }
    secret:          "%secret%"
    default_locale:  "%locale%"
    form:            ~
    csrf_protection: ~
    trusted_hosts:   ~
    trusted_proxies: ~
    fragments:       ~
    router:
        resource:            "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    templating:
        engines: [ "twig" ]
    session:
        handler_id:      ~
        cookie_lifetime: 31536000  # 1 year
    http_method_override: true

# Twig
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - "bootstrap_3_layout.html.twig"
        - "::OhGoogleMaps/google_maps_form_widget.html.twig"
    globals:
        google_analytics_enabled: "%google_analytics_enabled%"
        google_analytics_account: "%google_analytics_account%"
        google_maps_api_key:      "%google_maps_api_key%"
        project_title:            "%project_title%"
        admin_tag_version:        "2.6.2"

# Assetic
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ AppBundle ]

# Doctrine
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Doctrine Migrations
doctrine_migrations:
    dir_name:   "%kernel.root_dir%/../src/FinquesFarnos/AppBundle/DoctrineMigrations"
    namespace:  AppBundle\Migrations

# Stof Doctrine Extensions
stof_doctrine_extensions:
    default_locale:         "%locale%"
    translation_fallback:   true
    orm:
        default:
            translatable:   true
            softdeleteable: false
            timestampable:  true
            sluggable:      true

# Swiftmailer
swiftmailer:
    encryption: ssl
    auth_mode:  login
    transport:  "%mailer_transport%"
    host:       "%mailer_host%"
    username:   "%mailer_user%"
    password:   "%mailer_password%"
    spool:      { type: memory }

# Nelmio API Doc
nelmio_api_doc: ~

# Sensio Framework Extra
sensio_framework_extra:
    view:
        annotations: false

# FOS Rest
fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    view:
        view_response_listener: "force"

# FOS User
fos_user:
    db_driver:      orm
    firewall_name:  main
    user_class:     FinquesFarnos\UserBundle\Entity\User
    group:
        group_class:   FinquesFarnos\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager
    service:
        user_manager: sonata.user.orm.user_manager

# A2lix Translations
a2lix_translation_form:
    locales:          [ es, en, fr ]
    default_required: true
    manager_registry: doctrine
    templating:       "::A2lix/default.html.twig"

# JMS i18n Routing
jms_i18n_routing:
    default_locale: ca
    locales:        [ ca, es, en, fr ]
    strategy:       prefix

# KNP Paginator
knp_paginator:
    page_range: 10
    template:
        pagination: "KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig"

# Genemu
genemu_form:
    date: ~

# Recaptcha
ewz_recaptcha:
    public_key:  "%recaptcha_site_key%"
    private_key: "%recaptcha_secret%"

# Orkestra PDF
orkestra_pdf:
    tcpdf:
        root_dir:  "%kernel.root_dir%/../vendor/tecnickcom/tcpdf"
        fonts_dir: "%kernel.root_dir%/../vendor/tecnickcom/tcpdf/fonts"
