app_front:
    resource: '@AppBundle/Controller/FrontController.php'
    type:     annotation
    prefix:   /

app_api:
    resource: '@AppBundle/Controller/ApiController.php'
    type:     rest
    options:  { i18n: false }

_liip_imagine:
    resource: '@LiipImagineBundle/Resources/config/routing.xml'
    options:  { i18n: false }

admin:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix:   /admin
    options:  { i18n: false }

_sonata_admin:
    resource: .
    type:     sonata_admin
    prefix:   /admin
    options:  { i18n: false }

sonata_user_resetting:
    resource: "@SonataUserBundle/Resources/config/routing/admin_security.xml"
    prefix:   /admin
    options:  { i18n: false }

sonata_user_admin_resetting:
    resource: "@SonataUserBundle/Resources/config/routing/admin_resetting.xml"
    prefix:   /admin/resetting
    options:  { i18n: false }

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix:   /admin/resetting
    options:  { i18n: false }

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    options:  { i18n: false }

presta_sitemap:
    resource: '@PrestaSitemapBundle/Resources/config/routing.yml'
    prefix:   /
    options:  { i18n: false }

_redirecting_trailing_slashes:
    resource: "@AppBundle/Controller/RedirectingController.php"
    type:     annotation
    options:  { i18n: false }
