parameters:

services:
# Doctrine Listeners
    app.doctrine_listener:
        class: FinquesFarnos\AppBundle\EventListener\DoctrineListeners
        tags:
            - { name: doctrine.event_listener, event: prePersist }

# Orkestra PDF
    app.property_pdf_generator:
        class: FinquesFarnos\AppBundle\PdfGenerator\PropertyGenerator
        arguments: [ @orkestra.pdf.factory_registry, @templating ]

# Sonata Admin
    sonata.admin.slide:
        class: FinquesFarnos\AppBundle\Admin\ImageSliderAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Web", label: "Slides" }
        arguments:
            - ~
            - FinquesFarnos\AppBundle\Entity\ImageSlider
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle] ]
    sonata.admin.category:
        class: FinquesFarnos\AppBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Immoble", label: "Categories" }
        arguments:
            - ~
            - FinquesFarnos\AppBundle\Entity\Category
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle] ]
    sonata.admin.type:
        class: FinquesFarnos\AppBundle\Admin\TypeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Immoble", label: "Tipus" }
        arguments:
            - ~
            - FinquesFarnos\AppBundle\Entity\Type
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle] ]
    sonata.admin.image:
        class: FinquesFarnos\AppBundle\Admin\ImagePropertyAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Immoble", label: "Imatges" }
        arguments:
            - ~
            - FinquesFarnos\AppBundle\Entity\ImageProperty
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle] ]
    sonata.admin.property:
        class: FinquesFarnos\AppBundle\Admin\PropertyAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Immoble", label: "Immobles" }
        arguments:
            - ~
            - FinquesFarnos\AppBundle\Entity\Property
            - AppBundle:Admin/PropertyAdmin
        calls:
            - [ setTranslationDomain, [AppBundle] ]

# Sonata Block
    sonata.admin.block.visit_stats:
        class: FinquesFarnos\AppBundle\Admin\Block\VisitStatsBlockService
        tags:
            - { name: sonata.block }
        arguments:
            - sonata.admin.block.visit_stats
            - @templating
            - @doctrine.orm.entity_manager